# application name
spring.application.name=medi-care
# Profile
spring.profiles.active=local
# server port
#server.port=8080
#
## database configuration
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=
#
#
## JPA/Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=
#spring.jpa.show-sql=
#spring.jpa.properties.hibernate.format_sql=
#spring.jpa.open-in-view=
## Best Practice: Store in UTC, Display in IST
#spring.jpa.properties.hibernate.jdbc.time_zone=
## This handles N+1 globally by fetching collections in batches
#spring.jpa.properties.hibernate.default_batch_fetch_size=
#spring.data.web.pageable.serialization-mode=
#
## Focus on the Hikari level which actually controls the JDBC connection
#spring.datasource.hikari.auto-commit=
#spring.datasource.hikari.maximum-pool-size=
#spring.datasource.hikari.minimum-idle=
#
## Jackson / JSON Fixes
#spring.jackson.time-zone=
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=
#spring.jackson.default-property-inclusion=
#spring.jackson.deserialization.fail-on-unknown-properties=
## validation
#spring.validation.mode=
#
## security
##spring.security.user.name=admin
##spring.security.user.password=admin
#
## The name and path of the log file
#logging.level.org.springframework.web=
#logging.level.com.care.medi=
#logging.file.name=logs/medi-care.log
#logging.logback.rollingpolicy.max-file-size=
#logging.logback.rollingpolicy.max-history=
#logging.pattern.console=
#
## OpenAPI
## Change the Swagger UI path
#springdoc.swagger-ui.enabled=
## Define the JSON endpoint
#springdoc.api-docs.path=
## Define the UI endpoint
#springdoc.swagger-ui.path=
## Ensure your package is scanned
#springdoc.packages-to-scan=