# application name
spring.application.name=medi-care
# Profile
spring.profiles.active=local
# Port
server.port=8080

# database configuration
spring.datasource.url=
spring.datasource.password=
spring.datasource.driver-class-name=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false


# validation
spring.validation.mode=strict

# logging
logging.level.org.springframework.web=DEBUG
logging.level.com.care.medi=DEBUG
